#!/bin/bash
# Product Maker Cancel Script
# Stops the active product building loop

set -euo pipefail

STATE_FILE=".product-maker-state.yaml"
LOG_FILE=".product-maker/loop.log"

log() {
    if [[ -f "$LOG_FILE" ]]; then
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
    else
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
    fi
}

# Check if state file exists
if [[ ! -f "$STATE_FILE" ]]; then
    echo "No active product-maker loop found."
    echo "Nothing to cancel."
    exit 0
fi

# Read current state
CURRENT_ITERATION=$(grep "^current_iteration:" "$STATE_FILE" | sed 's/^current_iteration: *//')
MAX_ITERATIONS=$(grep "^max_iterations:" "$STATE_FILE" | sed 's/^max_iterations: *//')

log "Canceling product-maker loop..."
log "Progress at cancellation: $CURRENT_ITERATION/$MAX_ITERATIONS iterations"

# Deactivate the loop
sed -i 's/active: true/active: false/' "$STATE_FILE"

# Create cancellation report
cat > .product-maker/cancellation-report.md <<EOF
# Product Maker - Cancellation Report

**Canceled At**: $(date)
**Iterations Completed**: $CURRENT_ITERATION
**Max Iterations**: $MAX_ITERATIONS
**Status**: CANCELED BY USER 🛑

## State at Cancellation

The product building loop was manually canceled.

## Progress Made

$(git log --oneline -10 2>/dev/null || echo "No git commits found")

## What Happens Next

1. The loop will stop on the next iteration
2. All progress has been saved via git commits
3. You can review the work done so far
4. You can resume by running /product-maker:build-product again

## Files Preserved

- All code changes (committed to git)
- Loop logs (.product-maker/loop.log)
- State file (.product-maker-state.yaml)

## To Resume

Simply run /product-maker:build-product again with an updated or refined prompt.

---
Generated by Product Maker Plugin
EOF

log "Cancellation report created: .product-maker/cancellation-report.md"
log "Loop will stop after current iteration completes"

echo ""
echo "✅ Product Maker loop canceled"
echo ""
echo "Progress saved: $CURRENT_ITERATION iterations completed"
echo "All work has been committed to git"
echo ""
echo "Review your progress:"
echo "  git log --oneline -20"
echo ""
echo "Resume building:"
echo "  /product-maker:build-product \"<updated prompt>\" --max-iterations <N>"
echo ""
